package com.scivicslab.openmathlisp.symbols;

import com.scivicslab.openmathlisp.sexp.SExp;
import com.scivicslab.openmathlisp.sexp.SexpReader;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The symbol table: one {@link SymbolEntry} per OpenMath symbol, read from an s-expression file.
 * The bundled table is {@code openmath/symbols.lisp}, generated by {@code bin/generate-symbol-table.py}.
 */
public final class SymbolTable {

    private static final String RESOURCE = "openmath/symbols.lisp";

    private final Map<String, SymbolEntry> entries;

    private SymbolTable(Map<String, SymbolEntry> entries) {
        this.entries = Map.copyOf(entries);
    }

    /**
     * Loads the table bundled with the library.
     * @return the table
     */
    public static SymbolTable loadBundled() {
        try (InputStream in = SymbolTable.class.getClassLoader().getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException("missing resource " + RESOURCE);
            }
            return parse(new String(in.readAllBytes(), StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new IllegalStateException("cannot read " + RESOURCE, e);
        }
    }

    /**
     * Parses a table from its s-expression text.
     * @param text the text of a symbols file
     * @return the table
     * @throws SymbolTableFormatException when a row is malformed
     */
    public static SymbolTable parse(String text) {
        Map<String, SymbolEntry> entries = new LinkedHashMap<>();
        for (SExp row : SexpReader.readAll(text)) {
            SymbolEntry entry = parseRow(row);
            if (entries.containsKey(entry.qualifiedName())) {
                throw new SymbolTableFormatException("duplicate symbol " + entry.qualifiedName());
            }
            entries.put(entry.qualifiedName(), entry);
        }
        return new SymbolTable(entries);
    }

    private static SymbolEntry parseRow(SExp row) {
        if (!(row instanceof SExp.SList list) || list.items().isEmpty()
                || !(list.items().get(0) instanceof SExp.SSymbol head) || !head.name().contains(":")) {
            throw new SymbolTableFormatException("row must start with cd:name: " + row);
        }
        Map<String, SExp> fields = new LinkedHashMap<>();
        for (int i = 1; i + 1 < list.items().size(); i += 2) {
            if (!(list.items().get(i) instanceof SExp.SSymbol key) || !key.isKeyword()) {
                throw new SymbolTableFormatException(head.name() + ": expected keyword at position " + i);
            }
            fields.put(key.name(), list.items().get(i + 1));
        }
        if ((list.items().size() - 1) % 2 != 0) {
            throw new SymbolTableFormatException(head.name() + ": odd number of keyword/value items");
        }
        for (String required : List.of(":role", ":arity", ":latex", ":maxima", ":smt")) {
            if (!fields.containsKey(required)) {
                throw new SymbolTableFormatException(head.name() + ": missing " + required);
            }
        }
        Role role = Role.fromName(symbolName(head, fields.get(":role")));
        String arityText = symbolOrIntegerText(head, fields.get(":arity"));
        int arity = arityText.equals("nary") ? SymbolEntry.NARY : Integer.parseInt(arityText);
        Map<InputFormat, Rule> rules = new LinkedHashMap<>();
        for (InputFormat format : InputFormat.values()) {
            SExp value = fields.get(format.keyword());
            if (value instanceof SExp.SSymbol symbol && symbol.isNil()) {
                continue;
            }
            rules.put(format, parseRule(head, value));
        }
        if (!rules.containsKey(InputFormat.LATEX)) {
            throw new SymbolTableFormatException(head.name() + ": :latex must be a rule, not nil");
        }
        return new SymbolEntry(head.name(), role, arity, rules);
    }

    private static Rule parseRule(SExp.SSymbol head, SExp value) {
        if (!(value instanceof SExp.SList list) || list.items().isEmpty()
                || !(list.items().get(0) instanceof SExp.SSymbol kind)) {
            throw new SymbolTableFormatException(head.name() + ": rule must be a list starting with a keyword: " + value);
        }
        List<SExp> items = list.items();
        try {
            return switch (kind.name()) {
                case ":infix" -> new Rule.Infix(string(items.get(1)), integer(items.get(2)),
                        symbolName(head, items.get(3)).equals("right") ? Rule.Associativity.RIGHT : Rule.Associativity.LEFT);
                case ":prefix" -> new Rule.Prefix(string(items.get(1)), integer(items.get(2)));
                case ":function" -> new Rule.Function(string(items.get(1)));
                case ":template" -> new Rule.Template(string(items.get(1)), items.size() > 2 ? integer(items.get(2)) : null,
                        items.size() > 3 ? integer(items.get(3)) : null);
                case ":special" -> new Rule.Special(string(items.get(1)));
                default -> throw new SymbolTableFormatException(head.name() + ": unknown rule kind " + kind.name());
            };
        } catch (IndexOutOfBoundsException | ClassCastException e) {
            throw new SymbolTableFormatException(head.name() + ": malformed rule " + value, e);
        }
    }

    private static String symbolName(SExp.SSymbol head, SExp value) {
        if (value instanceof SExp.SSymbol symbol) {
            return symbol.name().startsWith(":") ? symbol.name().substring(1) : symbol.name();
        }
        throw new SymbolTableFormatException(head.name() + ": expected a symbol, found " + value);
    }

    private static String symbolOrIntegerText(SExp.SSymbol head, SExp value) {
        if (value instanceof SExp.SInteger integer) {
            return integer.value().toString();
        }
        return symbolName(head, value);
    }

    private static String string(SExp value) {
        return ((SExp.SString) value).value();
    }

    private static int integer(SExp value) {
        return ((SExp.SInteger) value).value().intValueExact();
    }

    /**
     * Tells whether a symbol is in the table.
     * @param qualifiedName {@code cd:name}
     * @return true when present
     */
    public boolean contains(String qualifiedName) {
        return entries.containsKey(qualifiedName);
    }

    /**
     * Looks up a symbol.
     * @param qualifiedName {@code cd:name}
     * @return the row
     * @throws IllegalArgumentException when the symbol is not in the table
     */
    public SymbolEntry get(String qualifiedName) {
        SymbolEntry entry = entries.get(qualifiedName);
        if (entry == null) {
            throw new IllegalArgumentException("symbol not in table: " + qualifiedName);
        }
        return entry;
    }

    /** @return all rows in file order */
    public Collection<SymbolEntry> entries() {
        return entries.values();
    }

    /** @return the number of rows */
    public int size() {
        return entries.size();
    }
}
