; Symbol table of openmath-lisp. GENERATED by bin/generate-symbol-table.py; edit RULES there.
; One list per symbol: role and arity come from the OpenMath .ocd/.sts files,
; :latex/:maxima/:smt are writing rules (nil = the format cannot express the symbol).

;;; arith1
(arith1:lcm
  :role application :arity nary
  :latex  (:function "\\operatorname{lcm}")
  :maxima (:function "lcm")
  :smt    nil)
(arith1:gcd
  :role application :arity nary
  :latex  (:function "\\gcd")
  :maxima (:function "gcd")
  :smt    nil)
(arith1:plus
  :role application :arity nary
  :latex  (:infix " + " 20 :left)
  :maxima (:infix "+" 20 :left)
  :smt    (:function "+"))
(arith1:unary_minus
  :role application :arity 1
  :latex  (:prefix "-" 40)
  :maxima (:prefix "-" 40)
  :smt    (:function "-"))
(arith1:minus
  :role application :arity 2
  :latex  (:infix " - " 20 :left)
  :maxima (:infix "-" 20 :left)
  :smt    (:function "-"))
(arith1:times
  :role application :arity nary
  :latex  (:infix " " 30 :left)
  :maxima (:infix "*" 30 :left)
  :smt    (:function "*"))
(arith1:divide
  :role application :arity 2
  :latex  (:template "\\frac{~1}{~2}")
  :maxima (:infix "/" 30 :left)
  :smt    (:function "/"))
(arith1:power
  :role application :arity 2
  :latex  (:special "power")
  :maxima (:infix "^" 50 :right)
  :smt    (:function "^"))
(arith1:abs
  :role application :arity 1
  :latex  (:template "\\left|~1\\right|")
  :maxima (:function "abs")
  :smt    nil)
(arith1:root
  :role application :arity 2
  :latex  (:special "root")
  :maxima (:template "(~1)^(1/(~2))")
  :smt    nil)
(arith1:sum
  :role application :arity 2
  :latex  (:template "\\sum_{~2.v1 = ~1.1}^{~1.2} ~2.b" 35 15)
  :maxima (:template "sum(~2.b, ~2.v1, ~1.1, ~1.2)")
  :smt    nil)
(arith1:product
  :role application :arity 2
  :latex  (:template "\\prod_{~2.v1 = ~1.1}^{~1.2} ~2.b" 35 15)
  :maxima (:template "product(~2.b, ~2.v1, ~1.1, ~1.2)")
  :smt    nil)

;;; relation1
(relation1:eq
  :role application :arity 2
  :latex  (:infix " = " 10 :left)
  :maxima (:infix " = " 10 :left)
  :smt    (:function "="))
(relation1:lt
  :role application :arity 2
  :latex  (:infix " < " 10 :left)
  :maxima (:infix " < " 10 :left)
  :smt    (:function "<"))
(relation1:gt
  :role application :arity 2
  :latex  (:infix " > " 10 :left)
  :maxima (:infix " > " 10 :left)
  :smt    (:function ">"))
(relation1:neq
  :role application :arity 2
  :latex  (:infix " \\neq " 10 :left)
  :maxima (:infix " # " 10 :left)
  :smt    (:function "distinct"))
(relation1:leq
  :role application :arity 2
  :latex  (:infix " \\leq " 10 :left)
  :maxima (:infix " <= " 10 :left)
  :smt    (:function "<="))
(relation1:geq
  :role application :arity 2
  :latex  (:infix " \\geq " 10 :left)
  :maxima (:infix " >= " 10 :left)
  :smt    (:function ">="))
(relation1:approx
  :role application :arity 2
  :latex  (:infix " \\approx " 10 :left)
  :maxima nil
  :smt    nil)

;;; transc1
(transc1:log
  :role application :arity 2
  :latex  (:template "\\log_{~1} ~2" 45)
  :maxima (:template "(log(~2)/log(~1))")
  :smt    nil)
(transc1:ln
  :role application :arity 1
  :latex  (:prefix "\\ln " 45)
  :maxima (:function "log")
  :smt    nil)
(transc1:exp
  :role application :arity 1
  :latex  (:template "e^{~1}")
  :maxima (:function "exp")
  :smt    nil)
(transc1:sin
  :role application :arity 1
  :latex  (:prefix "\\sin " 45)
  :maxima (:function "sin")
  :smt    nil)
(transc1:cos
  :role application :arity 1
  :latex  (:prefix "\\cos " 45)
  :maxima (:function "cos")
  :smt    nil)
(transc1:tan
  :role application :arity 1
  :latex  (:prefix "\\tan " 45)
  :maxima (:function "tan")
  :smt    nil)
(transc1:sec
  :role application :arity 1
  :latex  (:prefix "\\sec " 45)
  :maxima (:function "sec")
  :smt    nil)
(transc1:csc
  :role application :arity 1
  :latex  (:prefix "\\csc " 45)
  :maxima (:function "csc")
  :smt    nil)
(transc1:cot
  :role application :arity 1
  :latex  (:prefix "\\cot " 45)
  :maxima (:function "cot")
  :smt    nil)
(transc1:sinh
  :role application :arity 1
  :latex  (:prefix "\\sinh " 45)
  :maxima (:function "sinh")
  :smt    nil)
(transc1:cosh
  :role application :arity 1
  :latex  (:prefix "\\cosh " 45)
  :maxima (:function "cosh")
  :smt    nil)
(transc1:tanh
  :role application :arity 1
  :latex  (:prefix "\\tanh " 45)
  :maxima (:function "tanh")
  :smt    nil)
(transc1:sech
  :role application :arity 1
  :latex  (:prefix "\\operatorname{sech} " 45)
  :maxima (:function "sech")
  :smt    nil)
(transc1:csch
  :role application :arity 1
  :latex  (:prefix "\\operatorname{csch} " 45)
  :maxima (:function "csch")
  :smt    nil)
(transc1:coth
  :role application :arity 1
  :latex  (:prefix "\\operatorname{coth} " 45)
  :maxima (:function "coth")
  :smt    nil)
(transc1:arcsin
  :role application :arity 1
  :latex  (:prefix "\\arcsin " 45)
  :maxima (:function "asin")
  :smt    nil)
(transc1:arccos
  :role application :arity 1
  :latex  (:prefix "\\arccos " 45)
  :maxima (:function "acos")
  :smt    nil)
(transc1:arctan
  :role application :arity 1
  :latex  (:prefix "\\arctan " 45)
  :maxima (:function "atan")
  :smt    nil)
(transc1:arcsec
  :role application :arity 1
  :latex  (:prefix "\\operatorname{arcsec} " 45)
  :maxima (:function "asec")
  :smt    nil)
(transc1:arccsc
  :role application :arity 1
  :latex  (:prefix "\\operatorname{arccsc} " 45)
  :maxima (:function "acsc")
  :smt    nil)
(transc1:arccot
  :role application :arity 1
  :latex  (:prefix "\\operatorname{arccot} " 45)
  :maxima (:function "acot")
  :smt    nil)
(transc1:arcsinh
  :role application :arity 1
  :latex  (:prefix "\\operatorname{arcsinh} " 45)
  :maxima (:function "asinh")
  :smt    nil)
(transc1:arccosh
  :role application :arity 1
  :latex  (:prefix "\\operatorname{arccosh} " 45)
  :maxima (:function "acosh")
  :smt    nil)
(transc1:arctanh
  :role application :arity 1
  :latex  (:prefix "\\operatorname{arctanh} " 45)
  :maxima (:function "atanh")
  :smt    nil)
(transc1:arcsech
  :role application :arity 1
  :latex  (:prefix "\\operatorname{arcsech} " 45)
  :maxima (:function "asech")
  :smt    nil)
(transc1:arccsch
  :role application :arity 1
  :latex  (:prefix "\\operatorname{arccsch} " 45)
  :maxima (:function "acsch")
  :smt    nil)
(transc1:arccoth
  :role application :arity 1
  :latex  (:prefix "\\operatorname{arccoth} " 45)
  :maxima (:function "acoth")
  :smt    nil)

;;; calculus1
(calculus1:diff
  :role application :arity 1
  :latex  (:template "\\frac{d}{d~1.v1} ~1.b" 45)
  :maxima (:template "diff(~1.b, ~1.v1)")
  :smt    nil)
(calculus1:nthdiff
  :role application :arity 2
  :latex  (:template "\\frac{d^{~1}}{d~2.v1^{~1}} ~2.b" 45)
  :maxima (:template "diff(~2.b, ~2.v1, ~1)")
  :smt    nil)
(calculus1:partialdiff
  :role application :arity 2
  :latex  (:special "partialdiff")
  :maxima (:special "partialdiff")
  :smt    nil)
(calculus1:partialdiffdegree
  :role application :arity 3
  :latex  (:special "partialdiffdegree")
  :maxima nil
  :smt    nil)
(calculus1:int
  :role application :arity 1
  :latex  (:template "\\int ~1.b \\, d~1.v1" 35 15)
  :maxima (:template "'integrate(~1.b, ~1.v1)")
  :smt    nil)
(calculus1:defint
  :role application :arity 2
  :latex  (:template "\\int_{~1.1}^{~1.2} ~2.b \\, d~2.v1" 35 15)
  :maxima (:template "'integrate(~2.b, ~2.v1, ~1.1, ~1.2)")
  :smt    nil)

;;; fns1
(fns1:restriction
  :role application :arity 2
  :latex  (:template "\\operatorname{restriction}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(fns1:domainofapplication
  :role application :arity 1
  :latex  (:template "\\operatorname{domainofapplication}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(fns1:domain
  :role application :arity 1
  :latex  (:template "\\operatorname{domain}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(fns1:range
  :role application :arity 1
  :latex  (:template "\\operatorname{range}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(fns1:image
  :role application :arity 1
  :latex  (:template "\\operatorname{image}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(fns1:identity
  :role application :arity 1
  :latex  (:template "\\mathrm{id}")
  :maxima nil
  :smt    nil)
(fns1:left_inverse
  :role application :arity 1
  :latex  (:template "\\operatorname{left\\_inverse}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(fns1:right_inverse
  :role application :arity 1
  :latex  (:template "\\operatorname{right\\_inverse}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(fns1:inverse
  :role application :arity 1
  :latex  (:template "{~1}^{-1}" 50)
  :maxima nil
  :smt    nil)
(fns1:left_compose
  :role application :arity 2
  :latex  (:infix " \\circ " 35 :left)
  :maxima nil
  :smt    nil)
(fns1:lambda
  :role binder :arity 0
  :latex  (:template "\\left(~v \\mapsto ~b\\right)")
  :maxima (:template "lambda([~v], ~b)")
  :smt    nil)

;;; veccalc1
(veccalc1:divergence
  :role application :arity 1
  :latex  (:prefix "\\operatorname{div} " 45)
  :maxima nil
  :smt    nil)
(veccalc1:grad
  :role application :arity 1
  :latex  (:prefix "\\operatorname{grad} " 45)
  :maxima nil
  :smt    nil)
(veccalc1:curl
  :role application :arity 1
  :latex  (:prefix "\\operatorname{curl} " 45)
  :maxima nil
  :smt    nil)
(veccalc1:Laplacian
  :role application :arity 1
  :latex  (:prefix "\\nabla^{2} " 45)
  :maxima nil
  :smt    nil)

;;; nums1
(nums1:based_integer
  :role application :arity 2
  :latex  (:template "\\operatorname{based\\_integer}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(nums1:based_float
  :role application :arity 2
  :latex  (:template "\\operatorname{based\\_float}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(nums1:rational
  :role application :arity 2
  :latex  (:template "\\frac{~1}{~2}")
  :maxima (:template "((~1)/(~2))")
  :smt    (:function "/"))
(nums1:infinity
  :role constant :arity 0
  :latex  (:template "\\infty")
  :maxima (:template "inf")
  :smt    nil)
(nums1:e
  :role constant :arity 0
  :latex  (:template "e")
  :maxima (:template "%e")
  :smt    nil)
(nums1:i
  :role constant :arity 0
  :latex  (:template "i")
  :maxima (:template "%i")
  :smt    nil)
(nums1:pi
  :role constant :arity 0
  :latex  (:template "\\pi")
  :maxima (:template "%pi")
  :smt    nil)
(nums1:gamma
  :role constant :arity 0
  :latex  (:template "\\gamma")
  :maxima (:template "%gamma")
  :smt    nil)
(nums1:NaN
  :role constant :arity 0
  :latex  (:template "\\mathrm{NaN}")
  :maxima nil
  :smt    nil)

;;; minmax1
(minmax1:min
  :role application :arity 1
  :latex  (:function "\\min")
  :maxima (:function "min")
  :smt    nil)
(minmax1:max
  :role application :arity 1
  :latex  (:function "\\max")
  :maxima (:function "max")
  :smt    nil)

;;; integer1
(integer1:factorof
  :role application :arity 2
  :latex  (:template "\\operatorname{factorof}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(integer1:factorial
  :role application :arity 1
  :latex  (:template "{~1}!" 55)
  :maxima (:template "(~1)!")
  :smt    nil)
(integer1:quotient
  :role application :arity 2
  :latex  (:template "\\left\\lfloor \\frac{~1}{~2} \\right\\rfloor")
  :maxima (:template "quotient(~1, ~2)")
  :smt    nil)
(integer1:remainder
  :role application :arity 2
  :latex  (:infix " \\bmod " 30 :left)
  :maxima (:template "mod(~1, ~2)")
  :smt    nil)

;;; complex1
(complex1:complex_cartesian
  :role application :arity 2
  :latex  (:template "~1 + ~2 i" 20)
  :maxima (:template "(~1 + ~2*%i)")
  :smt    nil)
(complex1:real
  :role application :arity 1
  :latex  (:prefix "\\operatorname{Re} " 45)
  :maxima (:function "realpart")
  :smt    nil)
(complex1:imaginary
  :role application :arity 1
  :latex  (:prefix "\\operatorname{Im} " 45)
  :maxima (:function "imagpart")
  :smt    nil)
(complex1:complex_polar
  :role application :arity 2
  :latex  (:template "~1 e^{i ~2}" 30)
  :maxima (:template "(~1*exp(%i*~2))")
  :smt    nil)
(complex1:argument
  :role application :arity 1
  :latex  (:prefix "\\arg " 45)
  :maxima (:function "carg")
  :smt    nil)
(complex1:conjugate
  :role application :arity 1
  :latex  (:template "\\overline{~1}")
  :maxima (:function "conjugate")
  :smt    nil)

;;; limit1
(limit1:limit
  :role application :arity 3
  :latex  (:template "\\lim_{~3.v1 \\to ~1} ~3.b" 35 15)
  :maxima (:template "limit(~3.b, ~3.v1, ~1)")
  :smt    nil)
(limit1:both_sides
  :role constant :arity 0
  :latex  (:template "\\mathrm{both\\_sides}")
  :maxima nil
  :smt    nil)
(limit1:above
  :role constant :arity 0
  :latex  (:template "\\mathrm{above}")
  :maxima nil
  :smt    nil)
(limit1:below
  :role constant :arity 0
  :latex  (:template "\\mathrm{below}")
  :maxima nil
  :smt    nil)
(limit1:null
  :role constant :arity 0
  :latex  (:template "\\mathrm{null}")
  :maxima nil
  :smt    nil)

;;; linalg1
(linalg1:vectorproduct
  :role application :arity 2
  :latex  (:infix " \\times " 30 :left)
  :maxima nil
  :smt    nil)
(linalg1:scalarproduct
  :role application :arity 2
  :latex  (:infix " \\cdot " 30 :left)
  :maxima (:infix " . " 30 :left)
  :smt    nil)
(linalg1:outerproduct
  :role application :arity 2
  :latex  (:infix " \\otimes " 30 :left)
  :maxima nil
  :smt    nil)
(linalg1:transpose
  :role application :arity 1
  :latex  (:template "{~1}^{T}" 50)
  :maxima (:function "transpose")
  :smt    nil)
(linalg1:determinant
  :role application :arity 1
  :latex  (:prefix "\\det " 45)
  :maxima (:function "determinant")
  :smt    nil)
(linalg1:vector_selector
  :role application :arity 2
  :latex  (:template "{~2}_{~1}" 50)
  :maxima (:template "~2[~1]")
  :smt    nil)
(linalg1:matrix_selector
  :role application :arity 3
  :latex  (:template "{~3}_{~1 ~2}" 50)
  :maxima (:template "~3[~1, ~2]")
  :smt    nil)

;;; linalg2
(linalg2:vector
  :role application :arity nary
  :latex  (:template "\\begin{pmatrix} ~*{ \\\\ } \\end{pmatrix}")
  :maxima (:template "[~*]")
  :smt    nil)
(linalg2:matrixrow
  :role application :arity nary
  :latex  (:template "~*{ & }")
  :maxima (:template "[~*]")
  :smt    nil)
(linalg2:matrix
  :role application :arity nary
  :latex  (:template "\\begin{pmatrix} ~*{ \\\\ } \\end{pmatrix}")
  :maxima (:template "matrix(~*)")
  :smt    nil)

;;; interval1
(interval1:integer_interval
  :role application :arity 2
  :latex  (:template "\\left[~1, ~2\\right]")
  :maxima (:template "[~1, ~2]")
  :smt    nil)
(interval1:interval
  :role application :arity 2
  :latex  (:template "\\left[~1, ~2\\right]")
  :maxima (:template "[~1, ~2]")
  :smt    nil)
(interval1:oriented_interval
  :role application :arity 2
  :latex  (:template "\\left[~1 \\to ~2\\right]")
  :maxima (:template "[~1, ~2]")
  :smt    nil)
(interval1:interval_oo
  :role application :arity 2
  :latex  (:template "\\left(~1, ~2\\right)")
  :maxima (:template "[~1, ~2]")
  :smt    nil)
(interval1:interval_cc
  :role application :arity 2
  :latex  (:template "\\left[~1, ~2\\right]")
  :maxima (:template "[~1, ~2]")
  :smt    nil)
(interval1:interval_oc
  :role application :arity 2
  :latex  (:template "\\left(~1, ~2\\right]")
  :maxima (:template "[~1, ~2]")
  :smt    nil)
(interval1:interval_co
  :role application :arity 2
  :latex  (:template "\\left[~1, ~2\\right)")
  :maxima (:template "[~1, ~2]")
  :smt    nil)

;;; list1
(list1:map
  :role application :arity 2
  :latex  (:template "\\operatorname{map}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(list1:suchthat
  :role application :arity 2
  :latex  (:template "\\operatorname{suchthat}\\left(~*\\right)")
  :maxima nil
  :smt    nil)
(list1:list
  :role application :arity nary
  :latex  (:template "\\left[~*\\right]")
  :maxima (:template "[~*]")
  :smt    nil)

;;; private_reading1
(private_reading1:vectors
  :role attribution :arity 2
  :latex  nil
  :maxima nil
  :smt    nil)
(private_reading1:euler
  :role attribution :arity 2
  :latex  nil
  :maxima nil
  :smt    nil)
(private_reading1:imaginary
  :role attribution :arity 2
  :latex  nil
  :maxima nil
  :smt    nil)
(private_reading1:time
  :role attribution :arity 2
  :latex  nil
  :maxima nil
  :smt    nil)
(private_reading1:coordinates
  :role attribution :arity 2
  :latex  nil
  :maxima nil
  :smt    nil)
(private_reading1:functions
  :role attribution :arity 2
  :latex  nil
  :maxima nil
  :smt    nil)
